datauri/__init__.py,sha256=lpBJxJGVg9HmiWkaNNj3hkgwbrVWpzlmMiEb9KIEVbs,6297
datauri/__pycache__/__init__.cpython-311.pyc,,
datauri/__pycache__/exceptions.cpython-311.pyc,,
datauri/exceptions.py,sha256=kLO34fwvf2RtQINizi7iUTVhaRJwvJCgVWUyxkfRPB4,134
datauri/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
python_datauri-2.2.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
python_datauri-2.2.0.dist-info/LICENSE,sha256=fhLl30uuEsshWBuhV87SDhmGoFCN0Q0Oikq5pM-U6Fw,1211
python_datauri-2.2.0.dist-info/METADATA,sha256=sntvzcHONNJQ-_o-zMzHT_sr37sfN4eZum0YnNunes8,3323
python_datauri-2.2.0.dist-info/RECORD,,
python_datauri-2.2.0.dist-info/WHEEL,sha256=_4XEmVmaBFWtekSGrbfOGNjC2I5lUr0lZSRblBllIFA,109
python_datauri-2.2.0.dist-info/top_level.txt,sha256=x4QwzItArgb6RTqZUiCZsl-7E7Iwo6u0dkG54Pd_WaM,8
